config/routes.rb
require 'sidekiq/web'

Yaprom::Application.routes.draw do
	namespace :admin do
		get '/' => :index
		get :create_missing
		resources :projects, only: [:new, :create]
		resources :users, only: [:new, :create]
	end

	namespace :me do
		get '/' => :index
		post :password
		resources :ssh_keys, only: [:new, :create, :destroy]
	end

	get '/login' => 'site#login'
	post '/login' => 'site#auth'
	get '/logout' => 'site#logout'

	resources :users, only: [:show, :new, :create] do
		collection do
			get :find
		end
	end
	resources :projects, only: [:show, :new, :create] do
		post :add_member
	end
	resources :repos, only: [:show, :new, :create] do
		collection do
			get :access
		end
	end

	#mount Resque::Server, at: '/resque'
	mount Sidekiq::Web => '/sidekiq'
	root to: 'site#index'
end

app/views/admin/_project.html.erb
<%= form_for @project || Project.new, as: :project, url: admin_projects_path, html: { class: %w(form-horizontal) + clazz } do |f| %>
	<%= field_set_tag 'New project' do %>
		<div class="control-group">
			<%= f.label :name, 'Name', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_field :name, placeholder: 'Project name', required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :uid, 'UID', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_field :uid, placeholder: 'project-name', required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :description, 'Description', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_area :description, placeholder: 'Description of the project', rows: 5 %>
			</div>
		</div>
		<div class="control-group">
			<%= label_tag :scm, 'SCM', class: %w(control-label) %>
			<div class="controls">
				<%= select_tag 'project[scm]', options_for_select(
						[['Git', :git, 'data-image' => image_path('git.png')],
						 ['SVN', :svn, 'data-image' => image_path('svn.png')]]) %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= f.label :private, class: %w(checkbox) do %>
					<%= f.check_box :private %>
					Private
				<% end %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :owner, 'Owner', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_field :owner, placeholder: 'jdoe', required: true %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= f.submit class: %(btn btn-primary pull-right) %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/admin/create_missing.html.erb
<legend class="span6 center">
	Recreated projects
</legend>
<table class="table-striped table-bordered span6 center">
	<tbody>
	<% @created.each do |repo| %>
		<%= content_tag :tr do %>
			<td>
				<%= repo.virtual_path %>
			</td>
		<% end
	end %>
	</tbody>
</table>

app/views/admin/forbidden.html.erb
<div class="alert alert-error">
	<strong>Forbidden</strong> You're not allowed to access to this page.
</div>

app/views/admin/index.html.erb
<div class="row-fluid">
	<div class="span6">
		<%= render 'project', clazz: %w(full) %>
		<%= field_set_tag 'Create missing repos' do %>
			<%= link_to admin_create_missing_path do %>
				<button class="btn btn-primary pull-right">Create missing</button>
			<% end %>
		<% end %>
	</div>
	<%= render 'user', clazz: %w(span6) %>
</div>