config/routes.rb
require 'sidekiq/web'

Yaprom::Application.routes.draw do
	namespace :admin do
		get '/' => :index
		get :create_missing
		resources :projects, only: [:new, :create]
		resources :users, only: [:new, :create]
	end

	namespace :me do
		get '/' => :index
		post :password
		resources :ssh_keys, only: [:new, :create, :destroy]
	end

	get '/login' => 'site#login'
	post '/login' => 'site#auth'
	get '/logout' => 'site#logout'

	resources :users, only: [:show, :new, :create] do
		collection do
			get :find
		end
	end
	resources :projects, only: [:show, :new, :create] do
		post :add_member
	end
	resources :repos, only: [:show, :new, :create] do
		collection do
			get :access
		end
	end

	#mount Resque::Server, at: '/resque'
	mount Sidekiq::Web => '/sidekiq'
	root to: 'site#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
	acts_as_superclass

	attr_accessible :name, :uid, :description, :scm, :private, :public
	belongs_to :owner, class_name: User

	validates :name, length: {minimum: 5}, presence: true, uniqueness: true
	validates :uid, format: {with: /\A[a-z0-9-]+\z/}, length: {minimum: 5}, presence: true, uniqueness: true

	def self.real_class(scm)
		case scm
			when :git then GitProject
			when :svn then SvnProject
		end
	end

	def public=(public)
		self.private = !public
	end

	def public?
		!self.private?
	end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
	def create
		ActiveRecord::Base.transaction do
			owner = User.find_by_uid params[:project].delete :owner
			clazz = Project.real_class params[:project].delete(:scm).to_sym
			p clazz
			@project = clazz.new params[:project]
			@project.owner = owner
			if @project.save
				flash[:success] = 'Project created successfully'
				redirect_to admin_path
			end
		end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project = Project.new
	end

	def create
		ActiveRecord::Base.transaction do
			owner = User.find_by_uid params[:project].delete :owner
			clazz = Project.real_class params[:project].delete(:scm).to_sym
			p clazz
			@project = clazz.new params[:project]
			@project.owner = owner
			if @project.save
				flash[:success] = 'Project created successfully'
				redirect_to project_path @project
			else
				render :new
			end
		end
	end

	def show
		@project = Project.find params[:id]
		case @project.scm
			when :git then render 'git_projects/show'
		end
	end

	def add_member
		project = Project.find params[:project_id]
		params[:members].split(',').each do |member|
			member = User.find_by_uid member
			project.add_member member
		end
		redirect_to project_path project
	end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_add_members.html.erb
<div id="members-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>Add members</h3>
	</div>
	<%= form_tag project_add_member_path(@project), class: %w(form-horizontal form-compact) do %>
		<div class="modal-body">
			<div class="control-group">
				<%= label_tag :members, 'Members', class: %w(control-label) %>
				<div class="controls">
					<input type="text" id="members" name="members" />
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<input type="submit" class="btn btn-primary" value="Add"/>
		</div>
	<% end %>
</div>

app/views/projects/new.html.erb
<%= render 'application/errors', object: @project %>
<%= form_for @project, as: :project, url: projects_path, html: { class: %w(well form-horizontal form-compact span5 center) } do |f| %>
	<%= field_set_tag 'New project' do %>
		<div class="control-group">
			<%= f.label :name, 'Name', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_field :name, required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :uid, 'UID', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_field :uid, required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :description, 'Description', class: %w(control-label) %>
			<div class="controls">
				<%= f.text_area :description, rows: 5 %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :scm, 'SCM', class: %w(control-label) %>
			<div class="controls">
				<%= f.select :scm, [['Git', :git, 'data-image' => image_path('git.png')],
									['SVN', :svn, 'data-image' => image_path('svn.png')]] %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= f.label :private, class: %w(checkbox) do %>
					<%= f.check_box :private %>
					Private
				<% end %>
			</div>
		</div>
		<%= f.hidden_field :owner, value: @me.uid %>
		<div class="control-group">
			<div class="controls">
				<%= f.submit 'Sign in', class: %w(btn btn-primary pull-right) %>
			</div>
		</div>
	<% end %>
<% end %>