config/routes.rb
require 'sidekiq/web'

Yaprom::Application.routes.draw do
	namespace :admin do
		get '/' => :index
		get :create_missing
		resources :projects, only: [:new, :create]
		resources :users, only: [:new, :create]
	end

	namespace :me do
		get '/' => :index
		post :password
		resources :ssh_keys, only: [:new, :create, :destroy]
	end

	get '/login' => 'site#login'
	post '/login' => 'site#auth'
	get '/logout' => 'site#logout'

	resources :users, only: [:show, :new, :create] do
		collection do
			get :find
		end
	end
	resources :projects, only: [:show, :new, :create] do
		post :add_member
	end
	resources :repos, only: [:show, :new, :create] do
		collection do
			get :access
		end
	end

	#mount Resque::Server, at: '/resque'
	mount Sidekiq::Web => '/sidekiq'
	root to: 'site#index'
end

app/controllers/me/ssh_keys_controller.rb
class Me::SshKeysController < ApplicationController
	def new
		@content = ''
	end

	def create
		@content = params[:ssh_key_content]
		if @content.empty?
			file = params[:ssh_key_file]
			@content = file.read if file
		end
		@key = SshKey.create @me, @content
		flash[:success] = 'SSH key created successfully'
		redirect_to me_path
	rescue Exception => e
		flash[:error] = e.message
		render :new
	end

	def destroy
		ssh_key = SshKey.find params[:id]
		if ssh_key.user != @me
			flash[:error] = 'This key is not one of yours'
		else
			ssh_key.destroy
			flash[:success] = 'SSH key deleted successfully'
		end
		redirect_to me_path
	end
end

app/controllers/me_controller.rb
class MeController < ApplicationController
	def index
	end

	def password
		auth = Rails.configuration.auth_provider
		if params[:password_new] == params[:password_confirm]
			unless auth.authenticate @me.uid, params[:password_current]
				flash[:error] = 'Invalid password'
			else
				@me.password = User.hash_password params[:password_new]
				@me.save
				auth.change_password @me, params[:password_current], params[:password_new]
				flash[:success] = 'Password changed successfully'
			end
		else
			flash[:error] = 'Passwords don\'t match'
		end

		redirect_to me_path
	end
end

app/helpers/me/ssh_keys_helper.rb
module Me::SshKeysHelper
end

app/helpers/me_helper.rb
module MeHelper
end

app/views/me/_add_ssh-key.html.erb
<div id="ssh-key-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>Add SSH key</h3>
	</div>
	<%= form_tag me_ssh_keys_path, multipart: true, class: %w(form-horizontal form-compact) do %>
		<div class="modal-body">
			<div class="control-group">
				<%= label_tag :ssh_key_content, 'SSH key', class: %w(control-label) %>
				<div class="controls">
					<%= text_area_tag :ssh_key_content, @content, placeholder: 'Paste your SSH key here' %>
				</div>
			</div>
			<div class="control-group">
				<%= label_tag :ssh_key_file, 'Upload file', class: %w(control-label) %>
				<div class="controls">
					<%= file_field_tag :ssh_key_file, title: 'Browse' %>
				</div>
			</div>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<input type="submit" class="btn btn-primary" value="Add"/>
		</div>
	<% end %>
</div>

app/views/me/_change_password.html.erb
<div class="row-fluid">
	<%= form_tag me_password_path, class: %w(form-horizontal form-compact span8) do %>
		<%= field_set_tag 'Change password' do %>
			<div class="control-group">
				<%= label_tag :password_current, 'Current password', class: %w(control-label) %>
				<div class="controls">
					<%= password_field_tag :password_current, nil, placeholder: 'Current password', required: true %>
				</div>
			</div>
			<div class="control-group">
				<%= label_tag :password_new, 'New password', class: %w(control-label) %>
				<div class="controls">
					<%= password_field_tag :password_new, nil, placeholder: 'New password', required: true %>
				</div>
			</div>
			<div class="control-group">
				<%= label_tag :password_confirm, 'Confirm password', class: %w(control-label) %>
				<div class="controls">
					<%= password_field_tag :password_confirm, nil, placeholder: 'Confirm password', required: true %>
				</div>
			</div>
			<%= submit_tag 'Change password', class: %w(btn btn-danger pull-right) %>
		<% end
   end %>
</div>

app/views/me/_create_project.html.erb
<div id="project-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>New project</h3>
	</div>
	<%= form_for Project.new, html: {class: %w(form-horizontal form-compact)} do |f| %>
		<div class="modal-body">
			<div class="control-group">
				<%= f.label :name, 'Name', class: %w(control-label) %>
				<div class="controls">
					<%= f.text_field :name, required: true %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :uid, 'UID', class: %w(control-label) %>
				<div class="controls">
					<%= f.text_field :uid, required: true %>
				</div>
			</div>
			<div class="control-group">
				<%= f.label :description, 'Description', class: %w(control-label) %>
				<div class="controls">
					<%= f.text_area :description, rows: 5 %>
				</div>
			</div>
			<div class="control-group">
				<%= label_tag :scm, 'SCM', class: %w(control-label) %>
				<div class="controls">
					<%= select_tag 'project[scm]', options_for_select(
							[['Git', :git, 'data-image' => image_path('git.png')],
							 ['SVN', :svn, 'data-image' => image_path('svn.png')]]) %>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
					<%= f.label :private, class: %w(checkbox) do %>
						<%= f.check_box :private %>
						Private
					<% end %>
				</div>
			</div>
			<%= f.hidden_field :owner, value: @me.uid %>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<input type="submit" class="btn btn-primary" value="Create"/>
		</div>
	<% end %>
</div>

app/views/me/_list_projects.html.erb
<div class="row-fluid">
	<legend>
		My projects
		<%= link_to '#project-modal', role: :button, 'data-toggle' => :modal do
			image_tag 'empty.png', alt: 'Create project', class: 'sprite-silk-database_add'
		end %>
	</legend>
	<table class="table-striped table-bordered full">
		<thead>
		<tr>
			<th style="width: 0;"/>
			<th colspan="2">Project</th>
			<th style="width: 0;"/>
		</tr>
		</thead>
		<tbody>
		<% @me.participating_projects.each do |project| %>
			<tr>
				<td style="white-space: nowrap;">
					<%= image_tag "#{project.scm}-tiny.png", alt: project.scm %>
					<%= image_tag 'empty.png', alt: 'Owner', class: "sprite-silk-#{project.owner == @me ? 'award_star_gold_1' : 'empty'}" %>
					<%= image_tag 'empty.png', alt: 'Private', class: "sprite-silk-#{project.private ? 'lock' : 'empty'}" %>
				</td>
				<td><%= project.name %></td>
				<td><%= text_field_tag nil, project.repo_for(@me).clone_command, readonly: true, class: %w(cmd) %></td>
				<td>
					<%= link_to project_path project do
						image_tag 'empty.png', alt: 'Go to project', class: 'sprite-silk-database_go'
					end %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/me/_list_ssh_keys.html.erb
<div class="row-fluid">
	<legend>
		SSH keys
		<%= link_to '#ssh-key-modal', role: :button, 'data-toggle' => :modal do
			image_tag 'empty.png', alt: 'Add SSH key', class: 'sprite-silk-key_add'
		end %>
	</legend>
	<table class="table-striped table-bordered full">
		<thead>
		<tr>
			<th>Name</th>
			<th>Fingerprint</th>
			<th>Algorithm</th>
			<th>Size</th>
			<th style="width: 0;"/>
		</tr>
		</thead>
		<tbody>
		<% @me.ssh_keys.each do |key| %>
			<tr>
				<td><%= key.comment %></td>
				<td><%= key.fingerprint %></td>
				<td><%= key.key_type %></td>
				<td><%= key.size %></td>
				<td>
					<%= link_to me_ssh_key_path(key), method: :delete, confirm: 'Are you sure ?' do
						image_tag 'empty.png', alt: 'Delete SSH key', class: 'sprite-silk-key_delete'
					end %>
				</td>
			</tr>
		<% end %>
		</tbody>
	</table>
</div>

app/views/me/index.html.erb
<%= render 'add_ssh-key' %>
<%= render 'create_project' %>
<div class="row-fluid">
	<div class="span5">
		<%= render 'list_projects' %>
	</div>
	<div class="span7">
		<%= render 'change_password' %>
		<%= render 'list_ssh_keys' %>
	</div>
</div>