config/routes.rb
require 'sidekiq/web'

Yaprom::Application.routes.draw do
	namespace :admin do
		get '/' => :index
		get :create_missing
		resources :projects, only: [:new, :create]
		resources :users, only: [:new, :create]
	end

	namespace :me do
		get '/' => :index
		post :password
		resources :ssh_keys, only: [:new, :create, :destroy]
	end

	get '/login' => 'site#login'
	post '/login' => 'site#auth'
	get '/logout' => 'site#logout'

	resources :users, only: [:show, :new, :create] do
		collection do
			get :find
		end
	end
	resources :projects, only: [:show, :new, :create] do
		post :add_member
	end
	resources :repos, only: [:show, :new, :create] do
		collection do
			get :access
		end
	end

	#mount Resque::Server, at: '/resque'
	mount Sidekiq::Web => '/sidekiq'
	root to: 'site#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_filter :require_login

	def require_login
		if session[:me]
			@me = User.find session[:me]
		else
			flash[:error] = 'Authentication required'
			session[:from] = request.url
			redirect_to login_path
		end
	end

	def redirect_to_with_from(options = {}, response_status = {})
		from = params[:from] || session[:from]
		if from
			redirect_to from, response_status
		else
			redirect_to options, response_status
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def include_controller_meta_tags
		p controller_path
		[controller_path, "#{controller_path}-#{action_name}"].collect do |file|
			[javascript_include_tag_if_exists(file),
			stylesheet_link_tag_if_exists(file)]
		end.flatten().join("\n").html_safe
	end

	def asset_exists? file
		Yaprom::Application.assets.find_asset file
	end

	def javascript_include_tag_if_exists file
		javascript_include_tag(file) if asset_exists? "#{file}.js"
	end

	def stylesheet_link_tag_if_exists file
		stylesheet_link_tag(file) if asset_exists? "#{file}.css"
	end
end

app/views/application/_errors.html.erb
<% if object && object.errors.any? %>
	<div class="row-fluid">
		<div class="alert alert-error span6 offset3">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<strong><%= pluralize object.errors.count, 'error' %> prohibited
				this <%= object.class.to_s.downcase %> from being saved :</strong>
			<ul>
				<% object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	</div>
<% end %>

app/views/application/_flashs.html.erb
<% unless flash.empty? %>
<div id="flash" class="container">
<% [:error, :warning, :success, :info].each do |level|
	if flash[level] %>
		<%= content_tag :div, class: %(alert alert-#{level} fade in) do %>
			<%= button_tag 'x', type: 'button', class: 'close', data: { dismiss: "alert" } %>
			<%= flash[level] %>
		<% end
	end
end %>
</div>
<% end %>

app/views/application/_headers.html.erb
<header class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">
				<i class="icon-flag"></i>
				Yaprom
			</a>
			<ul class="nav">
			</ul>
			<ul class="nav pull-right">
				<% if @me %>
					<% if @me.admin? %>
					<li><%= link_to 'Admin', admin_path %></li>
					<% end %>
					<li><%= link_to "~#{@me.uid}", me_path %></li>
					<li>
						<%= link_to logout_path do %>
							<i class="icon-signout"></i>
							Logout
						<% end %>
					</li>
				<% else %>
					<% if YamlConfig['registration'] %>
						<li><%= link_to 'Sign in', new_user_path %></li>
					<% end %>
					<li>
						<%= link_to login_path do %>
							<i class="icon-signin"></i>
							Login
						<% end %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</header>

app/views/application/_user.html.erb
<%= form_for @user, :url => admin_users_path, html: { class: [:'form-horizontal', (defined?(span) ? span : :span5), (defined?(offset) ? offset : nil)] } do |f| %>
	<%= field_set_tag 'New user' do %>
		<div class="control-group">
			<%= f.label :common_name, 'Common name', class: :'control-label' %>
			<div class="controls">
				<%= f.text_field :common_name, placeholder: 'John', required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :surname, 'Surname', class: :'control-label' %>
			<div class="controls">
				<%= f.text_field :surname, placeholder: 'Doe', required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :uid, 'UID', class: :'control-label' %>
			<div class="controls">
				<%= f.text_field :uid, placeholder: 'jdoe', required: true %>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :password, 'Password', class: :'control-label' %>
			<div class="controls">
				<%= f.text_field :password, required: true %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<label class="checkbox">
					<%= check_box_tag :send_password_by_mail %>
					Send password by mail
				</label>
			</div>
		</div>
		<div class="control-group">
			<%= f.label :email, 'Email', placeholder: "john.doe@#{YamlConfig['email.domain']}", class: :'control-label' %>
			<div class="controls">
				<%= f.email_field :email, required: true %>
			</div>
		</div>
		<div class="control-group">
			<div class="controls">
				<%= f.submit class: :btn %>
			</div>
		</div>
		<%= hidden_field_tag :from, request.path %>
	<% end %>
<% end %>